### PR TITLE
Nova 4 support

### PR DESCRIPTION
**Pull request by rklugman**
Changed to Vue 3 and Tailwind CSS 3 and made some tweaks to the tool for new Nova component structure and CSS classes

### CODE REVIEW

**Comment by recycledbeans** [comment]
Cool, thanks. I'll pull the changes and review as soon as possible 👍🏻

**Comment by mateusgalasso** [comment]
Some update?

**Comment by miking7** [comment]
Keen to see this integrated as we've just updated to Nova 4 on one of our projects.  Are you guys likely to integrate this in the next few weeks, or should we start maintaining a fork?

**Comment by recycledbeans** [comment]
We're planning on having this merged and released as 2.0.0 by the end of the week.

**Comment by ThaDaVos** [comment]
So, that week passed - any eta? Just curious - we are currently working around it by just using a Nova Resource and a relation with the required models - also adding a custom nova action (inline)  for restore functionality

**Comment by recycledbeans** [comment]
Thanks for your patience, everyone! I have just merged and tagged v2.0.0.

I will be updating the documentation shortly.

**Pull request merged**
